Updating Contributing section
unicef/magasin pull request #42
Opened 2024-02-06 09:34 UTC by nathanbaleeta

- [ ] Updated grammar and few typos in docs/contributing/installer-dev.qmd

2024-02-07 12:19 UTC, merlos requested changes

2024-02-08 05:37 UTC, nathanbaleeta commented on docs/contributing/vulnerability-disclosure.qmd
> +Magasin team welcomes feedback from security researchers and the general public to help improve our security. If you happen to dicover a vulnerability, privacy issue, exposed data, or other security
Resolved in commit d7f45d9

2024-02-08 05:41 UTC, nathanbaleeta commented on docs/contributing/vulnerability-disclosure.qmd
> -- Assets or other equipment not owned by parties participating in this policy.
Resolved in commit 46e1f71

2024-02-08 05:45 UTC, nathanbaleeta commented on docs/contributing/vulnerability-disclosure.qmd
> +- Respond to your report promptly, and work with you to understand and validate your claim;
Resolved in commit 7135954

2024-02-08 07:03 UTC, merlos approved these changes

2024-02-08 07:03 UTC, merged